### ISSUE TITLE
electron-rebuild fails with an error

### ISSUE THREAD

**Issue by Antheso** [serenadeai/speech-recorder#1]
OS: Windows 10
Electron: v7.1.7
NodeJS: v12.13.1

```> electron-rebuild

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying portaudio/bin/portaudio_x64.dll to build/Release\portaudio_x64.dll
          1 file(s) copied.
  portaudio.cc
  GetDevices.cc
  AudioIn.cc
  common.cc
  win_delay_load_hook.cc
c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\portaudio.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\GetDevices.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]

  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\GetDevices.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\AudioIn.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\portaudio.cc)


c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\portaudio.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\AudioIn.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\GetDevices.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]

  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\portaudio.cc)
  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\AudioIn.cc)
  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\GetDevices.cc)
e:\code\test\node_modules\speech-recorder\src\Params.h(26): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
e:\code\test\node_modules\speech-recorder\src\Params.h(26): error C2512: 'Nan::Utf8String': no appropriate default constructor available (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
  e:\code\test\node_modules\speech-recorder\src\Params.h(26): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\AudioIn.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\code\test\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\code\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.1.7" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd E:\code\test\node_modules\speech-recorder
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1

Error: Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying portaudio/bin/portaudio_x64.dll to build/Release\portaudio_x64.dll
          1 file(s) copied.
  portaudio.cc
  GetDevices.cc
  AudioIn.cc
  common.cc
  win_delay_load_hook.cc
c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\portaudio.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\GetDevices.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8515): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]

  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\GetDevices.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\AudioIn.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\portaudio.cc)


c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\portaudio.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\AudioIn.cc)c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(8524): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\GetDevices.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]

  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\portaudio.cc)
  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\AudioIn.cc)
  c:\users\bohdan\.electron-gyp\7.1.7\include\node\v8.h(6919): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\GetDevices.cc)
e:\code\test\node_modules\speech-recorder\src\Params.h(26): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
e:\code\test\node_modules\speech-recorder\src\Params.h(26): error C2512: 'Nan::Utf8String': no appropriate default constructor available (compiling source file ..\src\AudioIn.cc) [E:\code\test\node_modules\speech-recorder\build\portaudio.vcxproj]
  e:\code\test\node_modules\speech-recorder\src\Params.h(26): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\AudioIn.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\code\test\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\code\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=7.1.7" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd E:\code\test\node_modules\speech-recorder
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\code\test\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (E:\code\test\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (E:\code\test\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (E:\code\test\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (E:\code\test\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (E:\code\test\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (E:\code\test\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (E:\code\test\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (E:\code\test\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (E:\code\gosu-desktop-electron\node_modules\rxjs\internal\Subscriber.js:145:22)```

**Comment by alectrocute** [comment]
@Antheso Did you ever find the problem?

**Comment by tmacwill** [comment]
Apologies for not responding to this! I think this might just be due to an older version of Electron? We're using this module in production with electron-rebuild and Electron v11.1.1.
